### PR TITLE
Update selenium version and remove IDEA files

### PR DESCRIPTION
**Pull request by Tsyklop**

### CODE REVIEW

**Comment by barancev** [comment]
I prefer to keep IDEA files in the repository, please don't attempt to remove them.

**Comment by barancev** [comment]
Also please don't mix cosmetic changes (like changing indentation and spaces) with functional ones in the same commit.

**Comment by Tsyklop** [comment]
Ok. Please fix [this](https://github.com/barancev/decorated-webdriver/issues/15) bug. I will close this pull request.

**Comment by Tsyklop** [comment]
Will you send new version to maven central?

**Comment by barancev** [comment]
Done, pushed to Sonatype, to be available in Maven central soon.

**Pull request closed without merging**
